company_x/config/routes.rb
Rails.application.routes.draw do

  resources :lessons

end

company_x/app/models/lesson.rb
class Lesson < ActiveRecord::Base
 has_many :parts
end

company_x/app/models/part.rb
class Part < ActiveRecord::Base
 belongs_to :lesson
end

company_x/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

company_x/app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
 def index
 	 @lessons = Lesson.all
 end

 def complete
 	@lesson = Lesson.find(params[:id])
 	@lesson.update(lesson_complete_params)
 	redirect_to 'index'

 end

 private
  def lesson_complete_params
  	params.require(:article).permit(:complete)	
  end

end

company_x/app/controllers/students_controller.rb
class StudentsController < ApplicationController
end

company_x/app/helpers/application_helper.rb
module ApplicationHelper
end

company_x/app/helpers/lessons_helper.rb
module LessonsHelper
end

company_x/app/helpers/students_helper.rb
module StudentsHelper
end

company_x/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CompanyX</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

company_x/app/views/lessons/index.html.erb
<h1> Welcome to the Lessons Page </h1>
<p> Please click on complete to complete lessons: </p>
<p> There are hundred lessons in total </p>

<table>
 <tr>
  <th>Lesson Title</th>
  <th>Action</th> 
</tr>
 <% @lessons.each do |lesson| %>
 <tr>	
  <td><%= lesson.title %>
  <td><%=link_to 'complete', lesson_path(lesson) %></td>
 </tr>
<% end %>